apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  namespace: lasample
  labels:
    app: helo
spec:
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: hello
        image: linuxacademycontent/gitops:hellov1.1
